import type { Metadata } from "next";
import Link from "next/link";
import ServicesShell from "../components/ServicesShell";
export const metadata: Metadata = { title: "Custom Business Software | Micro Titan", description: "Custom applications and ongoing operations for small businesses. Scope, build cost and monthly service agreed before work starts." };
const steps = [
 ["01", "Start with the work.", "We walk through the orders, appointments, estimates, or records you handle today. Together we choose the problem worth solving first."],
 ["02", "Agree on the build.", "You get a written scope, price, and acceptance criteria. Connections, data handling, support, and ongoing costs are part of that conversation."],
 ["03", "Try it as it takes shape.", "Review working previews along the way. We check the software against the agreed requirements and make room for your practical feedback."],
 ["04", "Keep it useful.", "The monthly service covers the ongoing operation we agree to provide. We define updates, monitoring, support, and recovery responsibilities before handover."]
];
export default function StudioPage() { return <ServicesShell><div className="wrap"><header className="pricing-intro"><p className="eyebrow">THE STUDIO / CUSTOM SOFTWARE</p><h1>A better way<br/><em>to do the work.</em></h1><p>Software shaped around your business: ordering, reservations, estimates, jobs, invoices, and the details that fall between them.</p><a className="button" href="mailto:hello@micro-titan.com?subject=Custom%20software%20for%20my%20business">Talk through your workflow ↗</a></header><section className="section"><div className="section-heading"><p className="eyebrow">BUILD IT. RUN IT. KEEP IMPROVING IT.</p><h2>Useful from the start.<br/>Supported after it.</h2><p>A custom app is an ongoing responsibility. We quote the initial build and the work of running it separately, so you know what each pays for.</p></div><div className="service-columns studio-steps">{steps.map(([number,title,description])=><article key={number}><span className="service-number">{number}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section><section className="services-faq"><h2>Clear scope. Clear expectations.</h2><details open><summary>What does a custom app cost?</summary><p>It depends on the workflow, integrations, and ongoing support. We provide a specific build price and recurring service price after scoping. Custom software is separate from the website and marketing package.</p></details><details><summary>How do you check the work?</summary><p>We define acceptance checks with you. Automated checks help test the software; practical workflow reviews establish whether it does the job you need. A passing software check alone is not proof of a business outcome.</p></details><details><summary>What happens to my data?</summary><p>We agree on hosting, access, exports, backups, and an exit plan as part of the scope. Any platform restrictions belong in that agreement, before you commit.</p></details></section><section className="closing"><h2>Start with the part<br/>that slows you down.</h2><a className="button" href="mailto:hello@micro-titan.com?subject=Custom%20software%20for%20my%20business">Tell us about it ↗</a><p className="fine-print">Looking for website and marketing services? <Link href="/pricing">See the published package.</Link></p></section></div></ServicesShell>; }
