import type { Metadata } from "next";
import ServicesShell from "../components/ServicesShell";
import ServiceQuote from "../components/ServiceQuote";
export const metadata: Metadata = { title: "Services & Pricing | Micro Titan", description: "Website and monthly care for small businesses: $2,500 setup and $750/month. See your quote without sharing your email." };
export default function PricingPage() {
  return <ServicesShell><div className="wrap"><header className="pricing-intro"><p className="eyebrow">SERVICES & PRICING</p><h1>Good work.<br/><em>Clear numbers.</em></h1><p>A standard website and monthly care for one business location: <strong>$2,500 setup + $750/month.</strong> Custom operations software is scoped separately.</p></header><ServiceQuote/><section className="services-faq"><h2>A few straight answers.</h2>
<details><summary>What does the monthly fee cover?</summary><p>Website care and updates, on-page local search setup, a monthly report of what changed, what was checked, and what needs your attention, four original social posts written for you, and a review request kit you send to your own customers. Your standard website is included in the setup fee. We agree on the detailed scope before you commit.</p></details>
<details><summary>What if I need software to run the business?</summary><p>We scope custom applications and their ongoing operation around your workflow. That is separate from this website and care package. We quote the build and recurring costs before work starts.</p></details>
<details><summary>Are advertising and content production included?</summary><p>Four original social posts a month are included and written for you. Advertising spend, photography, and video are not included. Any additional services and costs need an agreed scope.</p></details>
<details><summary>Will you guarantee rankings or revenue?</summary><p>No. We commit to the agreed work and report the results the available data supports. Search position and revenue cannot be promised.</p></details>
<details><summary>Are social posting and review requests included?</summary><p>Yes, with one boundary worth stating. We write four original posts a month and prepare a review request kit, and you approve everything before it goes out. Publishing to your accounts needs a posting role you grant us, and Google Business Profile management needs Manager access you grant us — an onboarding step, not an extra charge. Until then we hand you the posts and you publish. We never generate customer reviews, offer incentives, or filter requests so only happy customers are asked.</p></details>
<details><summary>When can we start?</summary><p>We agree on your scope and a start date together before you commit. Viewing a quote does not reserve a place or charge you.</p></details>
</section></div></ServicesShell>;
}
